FROM elonh/opde:scratch
LABEL maintainer="Elon Huang <elonhhuang@gmail.com>"

# 使用国内PIP镜像源
ARG CHINESE_PIP_MIRRORS=0
RUN [ $CHINESE_PIP_MIRRORS -eq 1 ] && \
	sudo -E -H pip3 config set global.index-url http://mirrors.aliyun.com/pypi/simple && \
	sudo -E -H pip3 config set install.trusted-host mirrors.aliyun.com

# running `poetry export -f requirements.txt -o requirements.txt` to update python packages
COPY ./requirements.txt /requirements.txt
RUN sudo -E -H pip3 install --no-cache-dir -r /requirements.txt \
	&& sudo -E rm -rf /root/.cache/* /requirements.txt

RUN curl -sL https://git.io/file-transfer | sh && \
	sudo mv ./transfer /usr/bin

ENV PATH="/opde:${PATH}"
# COPY . /opde
