FROM elonh/opde:scratch
LABEL maintainer="Elon Huang <elonhhuang@gmail.com>"

# 使用国内PIP镜像源
ARG CHINESE_PIP_MIRRORS=0
RUN [ $CHINESE_PIP_MIRRORS -eq 1 ] && \
	sudo -E -H pip3 config set global.index-url http://mirrors.aliyun.com/pypi/simple && \
	sudo -E -H pip3 config set install.trusted-host mirrors.aliyun.com || true

# running `poetry export -f requirements.txt -o requirements.txt` to update python packages
COPY ./requirements.txt /requirements.txt
RUN sudo -E -H pip3 install --no-cache-dir -r /requirements.txt \
	&& sudo -E rm -rf /root/.cache/* /requirements.txt

RUN curl -sL https://git.io/file-transfer | sh && \
	sudo mv ./transfer /usr/bin

RUN sudo -E apt-get update -y &&\
	sudo -E apt-get install -y --no-install-recommends \
	zsh ack tree \
	&& apt-get -y autoremove && apt-get clean \
	&& rm -rf /var/lib/apt/lists/* && rm -rf /root/.cache/*

RUN CHSH=no RUNZSH=no sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" && \
	sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="ys"/' ~/.zshrc && \
	git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions && \
	git clone https://github.com/zsh-users/zsh-history-substring-search ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-history-substring-search && \
	git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting && \
	git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions && \
	sed -i 's/plugins=(git)/plugins=(git zsh-syntax-highlighting zsh-completions history-substring-search zsh-autosuggestions)\nautoload -U compinit \&\& compinit/g' ~/.zshrc

ENV PATH="/opde:${PATH}"
# COPY . /opde
