
# kconfParseTab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'rootCONFIG DEFAULT EOL SYM TYPE VALUE\n        root : config\n             | root config\n        \n        config : CONFIG SYM EOL TYPE EOL properities\n        \n        properities : properity\n                    | properities properity\n        \n        properity : DEFAULT VALUE EOL\n        '
    
_lr_action_items = {'CONFIG':([0,1,2,4,9,10,12,14,],[3,3,-1,-2,-3,-4,-5,-6,]),'$end':([1,2,4,9,10,12,14,],[0,-1,-2,-3,-4,-5,-6,]),'SYM':([3,],[5,]),'EOL':([5,7,13,],[6,8,14,]),'TYPE':([6,],[7,]),'DEFAULT':([8,9,10,12,14,],[11,11,-4,-5,-6,]),'VALUE':([11,],[13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'root':([0,],[1,]),'config':([0,1,],[2,4,]),'properities':([8,],[9,]),'properity':([8,9,],[10,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> root","S'",1,None,None,None),
  ('root -> config','root',1,'p_list','kconfig.py',28),
  ('root -> root config','root',2,'p_list','kconfig.py',29),
  ('config -> CONFIG SYM EOL TYPE EOL properities','config',6,'p_config','kconfig.py',37),
  ('properities -> properity','properities',1,'p_dict','kconfig.py',46),
  ('properities -> properities properity','properities',2,'p_dict','kconfig.py',47),
  ('properity -> DEFAULT VALUE EOL','properity',3,'p_properity','kconfig.py',55),
]
